#!/bin/sh

case "$2" in
        up)
            sh $HOME/.config/polybar/scripts/network-networkmanager.sh --update
        ;;
        down)
            sh $HOME/.config/polybar/scripts/network-networkmanager.sh --update
        ;;
esac
